# Fundamentos de Linguagem Python Para Análise de Dados e Data Science

# Matemática e Manipulação de Matrizes com NumPy

![imagem](imagens/dsa_cap09.png)

In [1]:
# Versão da Linguagem Python
from platform import python_version
print("A versão da Linguagem Python usada neste Jupyter Notebook:", python_version())

A versão da Linguagem Python usada neste Jupyter Notebook: 3.9.13


## NumPy

[https://numpy.org/](https://numpy.org/)

In [13]:
# Importando o NumPy
import numpy as np

In [14]:
np.__version__

'1.21.5'

In [11]:
# Instrução para instalar uma versão exata do pacote em python
# !pip install numpy==1.22.2

### Criando Arrays NumPy

In [15]:
# Array criado a partir de um alista python
arr1 = np.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [16]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [17]:
# Um 9objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho
type(arr1)

numpy.ndarray

In [18]:
# Verificando o formato do array
arr1.shape

(9,)

Um array NumPy é uma estrutura de dados multidimensional usada em computação científica e análise de dados. o NumPy fornece um objeto de matriz N-dimensional (ndarray), que é uma grande homogênea de elementos, geralmente números, que podem ser indexados por um conjunto de inteiros.

Os arrays NumPy são mais eficientes do que as listas Python para armazenar e manipular grandes quantidades de dados, pois são implementadaos em Linguagem C e forne3cem várias otimizaç~´oes de desempenho. Além disso, o NumPy permite a fácil leitura e escrita de arquivos de dados, integração com outras bibliotecas Python e suporte a operações em paralelo usando várias CPUs e GPUs.

![imagem](imagens/formatos.png)

In [20]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [21]:
# Imprimindo um elemento específico no array
arr1[4]

48

In [22]:
# Indexação
arr1[1:4]

array([21, 32, 43])

In [23]:
# Indexação
arr1[1:4+1]

array([21, 32, 43, 48])

In [24]:
# Cria uma lista de índices
indices = [1, 2, 5, 6]

In [25]:
# Imp-0rimindo os elementos dos índices
arr1[indices]

array([21, 32, 15, 76])

In [26]:
# Cria uma máscara booleana para os elementos pares
mask = (arr1 % 2 == 0)

In [27]:
arr1[mask]

array([10, 32, 48, 76])

In [31]:
mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [28]:
# Alterando um elemento do array
arr1[0] = 100

In [29]:
print(arr1)

[100  21  32  43  48  15  76  57  89]


In [30]:
# Não é possível incluir elemento de outro tipo
try:
    arr1[0] = 'Novo Elemento'
except:
    print("Operação não permitida")

Operação não permitida


### Funções NumPy

In [32]:
# A função array() cria um array NumPy
arr2 = np.array([1, 2, 3, 4, 5])

In [33]:
print(arr2)

[1 2 3 4 5]


In [34]:
# Verificando o tipo do objeto
type(arr2)

numpy.ndarray

In [88]:
# Usando métodos do array NumPy
arr2.cumsum()

array([ 1,  3,  6, 10, 15], dtype=int32)

In [39]:
arr2.cumprod()

array([  1,   2,   6,  24, 120], dtype=int32)

In [58]:
# A função arange cria um array NumPy contendo uma progressão aritmética a partir de um intervalo - start, stop, step
arr3 = np.arange(0, 50, 5)

In [59]:
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [60]:
# Verificando o tipo do objeto
type(arr3)

numpy.ndarray

In [61]:
# Formato do array
np.shape(arr3)

(10,)

In [62]:
print(arr3.dtype)

int32


In [63]:
# Cria um array poreenchido com zeros
arr4 = np.zeros(10)

In [64]:
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [65]:
# Retorna 1 nas posições em diagonal e 0 nas restantes
arr5 = np.eye(3)

In [66]:
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [68]:
# Os valores passados como parâmetro, formam uma diagonal
arr6 = np.diag(np.array([1, 2, 3, 4]))

In [69]:
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [74]:
arr7 = np.array([True, False, False, True])

In [75]:
print(arr7)

[ True False False  True]


In [77]:
# Array de strings
arr8 = np.array(['Linaguagem Python', 'Linguagem R', 'Linguagem Julia'])

In [78]:
print(arr8)

['Linaguagem Python' 'Linguagem R' 'Linguagem Julia']


A função linspace() do NumPy é usada para criar uma sequência de números igualmente espaçados dentro de um intervalo especificado. Essa função é ampolamente utilizada em programação científica e matemática para gerar arrays de números para diversos fins, como gráficos, cálculos e simulações

O método linspace (linearly space vector) retorna um n´~umero de valores igualmente distribuídos no intervalo especificado.

In [79]:
print(np.linspace(0, 10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [80]:
print(np.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


A função logspace() do NumPy é usada para criar uma sequência igualmente espaçados em escala logarítmica dentro de um intervalo especificado. Essa função é amplamente utilizada em programação científica e matemática para gerar arrays de números para diversos fins, como gráficos, cálculos e simulações

In [82]:
print(np.logspace(0, 5, 10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


### Manipulando Matrizes

In [96]:
# Criando uma matriz
arr9 = np.array([[1, 2, 3], [4, 5, 6]])

In [97]:
type(arr9)

numpy.ndarray

In [98]:
print(arr9)

[[1 2 3]
 [4 5 6]]


In [99]:
print(arr9.shape)

(2, 3)


In [100]:
# Criando uma matriz 2x3 apenas com números 1
arr10 = np.ones((2, 3))

In [101]:
print(arr10)

[[1. 1. 1.]
 [1. 1. 1.]]


In [102]:
# Lista de Listas
lista = [[13, 81, 22], [0, 34, 59], [21, 48, 91]]

In [103]:
print(lista)

[[13, 81, 22], [0, 34, 59], [21, 48, 91]]


In [104]:
# A função matrix cria uma matriz a partir de uma lista de lista
arr11 = np.matrix(lista)

In [105]:
type(arr11)

numpy.matrix

In [106]:
print(arr11)

[[13 81 22]
 [ 0 34 59]
 [21 48 91]]


In [112]:
np.shape(arr11)

(3, 3)

In [113]:
arr11.size

9

In [114]:
print(arr11.dtype)

int32


In [115]:
print(arr11)

[[13 81 22]
 [ 0 34 59]
 [21 48 91]]


In [117]:
# Indexação da matriz
arr11[2, 1]

48

In [119]:
# Indexação da matriz]
arr11[0:2, 2]

matrix([[22],
        [59]])

In [121]:
# Indexação da matriz
arr11[1]

matrix([[ 0, 34, 59]])

In [122]:
# Alterando uma elemento da matriz
arr11[1, 0] = 100

In [123]:
print(arr11)

[[ 13  81  22]
 [100  34  59]
 [ 21  48  91]]


In [127]:
x = np.array([1, 2]) # NumPy decide o tipo dos dados
y = np.array([1.0, 2.0]) # NumPy decide o tipo dos dados
z = np.array([1, 2], dtype = np.float64) # Forçamos um tipo de dado em particular

In [128]:
print(x.dtype, y.dtype, z.dtype)

int32 float64 float64


In [129]:
arr12 = np.array([[24, 76, 92, 14], [47, 35, 89, 2]], dtype = float)

In [130]:
print(arr12)

[[24. 76. 92. 14.]
 [47. 35. 89.  2.]]


O itemsize de um array NumPy é um atributo que retorna o tamanho em bytes de cada elemento do array. Em outras palavras, o itemsize representa o número de bytes necessários para armazenar cada valor do array NumPy

In [131]:
arr12.itemsize

8

In [132]:
arr12.nbytes

64

In [133]:
arr12.ndim

2

### Manipulando Objetos de 3 e 4 dimensões no NumPy

In [134]:
# Cria um array NumPy de 3 dimensões
arr_3d = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

In [135]:
print(arr_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [136]:
arr_3d.ndim

3

In [137]:
arr_3d.shape

(2, 3, 4)

In [144]:
arr_3d[0, 2, 1]

10

<>:17: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:17: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\Alexandre\AppData\Local\Temp\ipykernel_1992\1620802604.py:17: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [


TypeError: list indices must be integers or slices, not tuple

In [146]:
arr_4d.itemsize

4

In [147]:
arr_4d.nbytes

240

In [154]:
# Cria um array NumPy de 4 dimensões
arr_4d = np.array(
[
    [
        [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10],
            [11, 12, 13, 14, 15],
            [16, 17, 18, 19, 20]
        ],
        [
            [21, 22, 23, 24, 25],
            [26, 27, 28, 29, 30],
            [31, 32, 33, 34, 35],
            [36, 37, 38, 39, 40]
        ],
        [
            [41, 42, 43, 44, 45],
            [46, 47, 48, 49, 50],
            [51, 52, 53, 54, 55],
            [56, 57, 58, 59, 60]
        ],
    ],
    [
        [
            [61, 62, 63, 64, 65],
            [66, 67, 68, 69, 70],
            [71, 72, 73, 74, 75],
            [76, 77, 78, 79, 80]
        ],
        [
            [81, 82, 83, 84, 85],
            [86, 87, 88, 89, 90],
            [91, 92, 93, 94, 95],
            [96, 97, 98, 99, 100]
        ],
        [
            [101, 102, 103, 104, 105],
            [106, 107, 108, 109, 110],
            [111, 112, 113, 114, 115],
            [116, 117, 118, 119, 120]
        ]
    ]
])

In [155]:
print(arr_4d)

[[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]]

  [[ 21  22  23  24  25]
   [ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]]

  [[ 41  42  43  44  45]
   [ 46  47  48  49  50]
   [ 51  52  53  54  55]
   [ 56  57  58  59  60]]]


 [[[ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]
   [ 76  77  78  79  80]]

  [[ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]

  [[101 102 103 104 105]
   [106 107 108 109 110]
   [111 112 113 114 115]
   [116 117 118 119 120]]]]


In [156]:
arr_4d.ndim

4

In [158]:
arr_4d.shape

(2, 3, 4, 5)

In [159]:
arr_4d[0, 2, 1]

array([46, 47, 48, 49, 50])

In [160]:
arr_4d[0, 2, 1, 4]

50