# Fundamentos de Linguagem Python Para Análise de Dados e Data Science

# Matemática e Manipulação de Matrizes com NumPy

![imagem](imagens/dsa_cap09.png)

In [1]:
# Versão da Linguagem Python
from platform import python_version
print("A versão da Linguagem Python usada neste Jupyter Notebook:", python_version())

A versão da Linguagem Python usada neste Jupyter Notebook: 3.9.13


## NumPy

[https://numpy.org/](https://numpy.org/)

In [13]:
# Importando o NumPy
import numpy as np

In [14]:
np.__version__

'1.21.5'

In [11]:
# Instrução para instalar uma versão exata do pacote em python
# !pip install numpy==1.22.2

### Criando Arrays NumPy

In [15]:
# Array criado a partir de um alista python
arr1 = np.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [16]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [17]:
# Um 9objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho
type(arr1)

numpy.ndarray

In [18]:
# Verificando o formato do array
arr1.shape

(9,)

Um array NumPy é uma estrutura de dados multidimensional usada em computação científica e análise de dados. o NumPy fornece um objeto de matriz N-dimensional (ndarray), que é uma grande homogênea de elementos, geralmente números, que podem ser indexados por um conjunto de inteiros.

Os arrays NumPy são mais eficientes do que as listas Python para armazenar e manipular grandes quantidades de dados, pois são implementadaos em Linguagem C e forne3cem várias otimizaç~´oes de desempenho. Além disso, o NumPy permite a fácil leitura e escrita de arquivos de dados, integração com outras bibliotecas Python e suporte a operações em paralelo usando várias CPUs e GPUs.

![imagem](imagens/formatos.png)

In [20]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [21]:
# Imprimindo um elemento específico no array
arr1[4]

48

In [22]:
# Indexação
arr1[1:4]

array([21, 32, 43])

In [23]:
# Indexação
arr1[1:4+1]

array([21, 32, 43, 48])

In [24]:
# Cria uma lista de índices
indices = [1, 2, 5, 6]

In [25]:
# Imp-0rimindo os elementos dos índices
arr1[indices]

array([21, 32, 15, 76])

In [26]:
# Cria uma máscara booleana para os elementos pares
mask = (arr1 % 2 == 0)

In [27]:
arr1[mask]

array([10, 32, 48, 76])

In [31]:
mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [28]:
# Alterando um elemento do array
arr1[0] = 100

In [29]:
print(arr1)

[100  21  32  43  48  15  76  57  89]


In [30]:
# Não é possível incluir elemento de outro tipo
try:
    arr1[0] = 'Novo Elemento'
except:
    print("Operação não permitida")

Operação não permitida
